# Generated by Django 5.2.7 on 2025-12-14 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercommunity',
            name='community_picture',
            field=models.ImageField(blank=True, null=True, upload_to='community_picture/'),
        ),
    ]
