# Generated by Django 5.2.7 on 2025-12-14 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_userpicture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpicture',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pictures/default.jpg', null=True, upload_to='profile_pictures/'),
        ),
    ]
